### ISSUE TITLE
如何更新擴充此配方內詞庫？

### ISSUE THREAD

**Issue by laubonghaudoi** [rime/rime-jyutping#12]
經過一段時間的使用，我通過小狼毫的用戶詞典管理導出了上萬條詞條。如果能將以上詞條加入本配方詞庫中，能提高粵拼方案的易用性。請問如果要擴充本配方詞庫，是否直接pull request更改`.dict.yaml`即可？是否需要遵循一定規範？

**Comment by lotem** [comment]
現在沒人主持粵拼詞庫的修訂，少量添加可以發出 Pull request 找 @LEOYoon-Tsaw 審覈。 
但我不建議一次匯入上萬詞條，一來 Diff 不容易看，二來不經篩選可能有私人數據或質量不高的詞條。

我構思了一套機制：
https://github.com/rime/plum/issues/5
這個構思是面向用戶的，需要一些軟件支持。

**Comment by laubonghaudoi** [comment]
感謝指導。那麼請問目前粵拼和其他方案是否有正在進行的詞典共享計劃呢？每一期計劃是否以issue的形式來呈現？儘管我導出了上萬條詞彙，實際上獨屬於粵拼方案且有效的估計也不過千條左右，大多是無用詞彙、私人數據或需要加入到八股文中的詞彙。我會人工檢閱詞條，保證其準確性再向此倉庫pull request。

**Comment by lotem** [comment]
如果做數據處理不費力，建議先整理出最高頻的，不必求多～

**Comment by laubonghaudoi** [comment]
瞭解，我整理好後先找@LEOYoon-Tsaw審閱。另外我會儘量找其他人加入此詞庫整理工作中。

**Comment by laubonghaudoi** [comment]
@lotem 我最近聯繫到一些能向此字庫貢獻的人士，需要進一步瞭解審閱的細節。請問有沒有@LEOYoon-Tsaw的聯繫郵箱或者其他聯繫方式？希望能夠和他進一步詳細討論
