### ISSUE TITLE
是否應該加入對開合口不分、泥來不分的懶音支持？

### ISSUE THREAD

**Issue by laubonghaudoi** [rime/rime-jyutping#14]
我新開了一個beta分支，用於每次更新時的測試和討論。在本次提交中我加入了對開合口不分懶音的兼容，但我無法確定此功能是否必要，希望聽取各位意見。

目前港式粵語中有較普遍的開合口不分的懶音現象，例如 「國家」/gwok gaa/ 會發成 /gok gaa/，「廣州」/gwong zau/ 發成 /gong zau/。本次提交https://github.com/rime/rime-jyutping/commit/128cca72af5e691d01049d6572171682833e5010 即是增加對此類懶音的識別。如果大家認爲有必要加入此懶音的識別，則可合併此分支到master中。若維持原狀，則用戶必須輸入正確發音，此分支可刪除。

**Comment by vatnid** [comment]
如果唔分 gw/kw 就連 n/l 都要允許埋，唔係會有啲唔一致

**Comment by laubonghaudoi** [comment]
> 如果唔分 gw/kw 就連 n/l 都要允許埋，唔係會有啲唔一致

如果確定支持懶音，會在之後的更新中陸續加入。

**Comment by chaaklau** [comment]
現時嘅兼容係針對 **系統拼寫規則** ，唔係發音、口音差異。
每個人嘅語音差異唔同。有啲人唔分長短（aa = a），有啲人唔分 kw-/k-, gw-/g-，有啲人唔分 -t/-k, -ng/-n。太多兼容的話會對區分嘅人造成不便。

不如提供合流嘅項目，等唔熟 regex 嘅人都用得到，但係預設係 comment out，有需要嘅人可以自己 uncomment？

**Comment by laubonghaudoi** [comment]
> 現時嘅兼容係針對 **系統拼寫規則** ，唔係發音、口音差異。
> 每個人嘅語音差異唔同。有啲人唔分長短（aa = a），有啲人唔分 kw-/k-, gw-/g-，有啲人唔分 -t/-k, -ng/-n。太多兼容的話會對區分嘅人造成不便。
> 
> 不如提供合流嘅項目，等唔熟 regex 嘅人都用得到，但係預設係 comment out，有需要嘅人可以自己 uncomment？

如果係噉，啱先提交咗一個新版本，可以測試一下https://github.com/rime/rime-jyutping/commit/60adb3e79076f337dfa7c7a721d8536faff0c344

其中兩種懶音（泥來、開合口）比較普遍，可以確定加入，但係對於疑影不分，我認爲唔可以單純噉加條規則來支持，因爲碼表入邊本身就將所有零聲母同疑母嘅字都分成兩份。係唔係應該將呢一類字嘅發音刪剩一個正音，然後再用規則來添加疑影不分嘅支援？

**Comment by sgalal** [comment]
可以開一個 Pull Request，喺 Pull request 入便討論是否 merge

#15

**Comment by laubonghaudoi** [comment]
總結一下目前討論的結果，綜合各方觀點，當前一致認同的是：方案中**默認不支持任何懶音**，但是可以在方案中加入註釋掉的懶音簡寫規則，作爲可選項。用戶想要兼容某一懶音規則（如n/l不分等）則自行取消註釋該行再部署。


但是現在仍有疑問的是，這些可選懶音規則，總共有幾條？目前可以確定的有：
1. n- / l- 不分（泥來不分）
2. (g|k)w- / (g|k)- 不分（開合口不分）

不能確定的有：
1. ng- / 0- 不分（疑影不分）
2. -a- / -aa- 不分（內外轉不分）
3. -n / -ng 不分（前後鼻音不分）


@lotem  對於第一點，想請問一事。即目前碼表中有一個令人困惑的現象，所有的ng- / 0-聲母的字都會一式兩份收錄兩種發音。例如:
```yaml
亚	aa
亚	ngaa
# ...
外	ngoi
外	oi
# ...
```
但是對於n- l- 和gw- kw- 聲母的字卻不見得一式兩份都收錄進來。例如只收錄`你 nei`但沒有`你 lei`我想問一下這是否出於原碼表作者的其他考慮？經過討論後大家比較認可的方案是：將這些一式兩份的ng- / 0- 字都刪去多餘的發音，只留下正音，然後依靠懶音運算規則來兼容，不知意下如何。

對於-a- / -aa-不分和-n / -ng不分，我個人傾向於不要加入，因爲此類懶音較少見且會大幅提高重碼率，加入後可能會誤導用戶。

**Comment by chowhoyin** [comment]
支持總結嘅結果～

**Comment by LEOYoon-Tsaw** [comment]
這個不建議在碼表裡改，方案裡用規則衍生就行了
