### ISSUE TITLE
第二批疑影不分字

### ISSUE THREAD

**Issue by laubonghaudoi** [rime/rime-jyutping#16]
在更新完第一批疑影不分的字後，我整理出了第二批字，大多爲生僻字。其中部分字在粵語審音配詞字庫和廣韻中查到的發音有衝突，故無法確定取捨，希望能提供修改意見。

```tsv
娭	aai
娭	ngaai
譺	aai
譺	jik
譺	ngaai
搹	aak
搹	ngak
轭	aak
轭	ngaak
鈪	aak
鈪	ngaak
贋	ngaam
贋	ngam
贋	ngan
晏	aan
晏	ngaan	1000
鴳	aan
鴳	ngaan
猒	aat
猒	jim
猒	ngaat
拗	aau
拗	ngaau
靿	aau
靿	ngaau
豷	ai
豷	ngai
躷	ai
躷	ngai
啽	am
啽	ngam
啽	ngap
韽	am
韽	ngam
𡁏	am
𡁏	ngam
噏	ap
噏	ngap
扤	at
扤	ngaat
扤	ngat
勾	au
勾	gau
勾	ngau
鉤	au
鉤	gau
鉤	ngau
鏂	au
鏂	ngau
𩥋	au
𩥋	ngau
哦	o
銨	ngon
銨	on
璦	ngoi
璦	oi
嶴	ngou
嶴	ou
擙	ngou
擙	ou
爊	ngou
爊	ou
芺	ngou
芺	ou
鏖	ngou
鏖	ou
```
@chaaklau
@leimaau
@sgalal

**Comment by leimaau** [comment]
我的覈對如下：
-----去掉-------
娭	aai（《康熙字典》倚亥切，音唉，《漢語大字典》不收）
娭	ngaai
譺	aai（《廣韻》五介切，形旁「疑」已經暗示疑母）
搹	ngak（同「扼/㧖」字）
㧖	zim
轭	ngaak
鈪	ngaak
贋	aam
贋	am
贋	ngaam
贋	ngam
贋	ngan
晏	ngaan
鴳	ngaan
猒	ngaat
拗	ngaau
靿	ngaau
豷	ngai
躷	ngai
韽	ngam
噏	ap（訓讀字，胡說，特例，ngap1音見《廣州話正音字典》、《實用廣州話分類詞典》以及各粵語片區共時比較）
勾	au
鉤	au
鏂	ngau
𩥋	au
銨	ngon
璦	ngoi
嶴	ngou
擙	ngou
芺	ngou
𡁏	am （同「𧭊」字，《集韻》謨蓬切=>mung4，口語訓讀，嬰兒的軟米飯之類食品，底層來源可能是壯侗，不少粵語區讀mung1，《古壯字字典》[boŋ]，建議刪除am1，保留ngam1，口語中對嬰兒會說「食mam1 mam1啊」或「食ngam1 ngam1 啊」，也作「𩜠」字，查「𩜠」字有mam1/ngam1兩音，對應得上）
-----補充-------
娭	hei（《廣韻》許其切）
搹	ak（同「扼/㧖」字，一般廣州話清紐內轉字讀/ɐ/，清紐外轉字讀/a/，但是例外不少，例如梗攝二等字具有文白異讀，文讀/ɐ/，白讀/a/，白讀反映早期形態，而特例中還有特例，影母梗二字早在1782年《分韻撮要》中混入曾攝，「阨扼厄軛鈪」從祖語的[ak]先後分化「阨扼厄[ɐk]/軛鈪[ak]」，具體可以參見陳三蘇《廣州話的上入和中入》、《第14屆粵方言國際學術研討會論文集》——黃得深[廣州話中入調與長短元音字規律再探]）
贋	ngaan（只此一音）
爊	ngaau(此字本身讀ou，ngou音來源「熬」，作異讀，白讀保留豪韻，可以把ngou、ngaau調低詞頻)
𡁏  mung
------修改-----
鏖	ngou  可以調低詞頻，大部分字典皆收，作又音
 句勾鉤鈎   gau，避諱，可調低詞頻

**Comment by laubonghaudoi** [comment]
已根據@leimaau 的意見提交修改，最終的修改方案請見https://github.com/rime/rime-jyutping/pull/17
