### ISSUE TITLE
Pronunciation for 「伺服器」 in dictionary

### ISSUE THREAD

**Issue by Raymonf** [rime/rime-jyutping#23]
The dictionary does not have "si fuk hei" as a valid pronunciation for 「伺服器」. Instead, "zi fuk hei" must be typed for predictions.

* https://words.hk/zidin/%E4%BC%BA%E6%9C%8D%E5%99%A8
* https://en.wiktionary.org/wiki/%E4%BC%BA%E6%9C%8D%E5%99%A8

**Comment by laubonghaudoi** [comment]
本倉庫已經暫停維護，入邊嘅錯音都唔會再修復。請改用我哋最新版嘅帶聲調碼表：[rime-cantonese](https://github.com/rime/rime-cantonese)

本碼表`rime-jyutping`可能會喺未來某一日由`rime-cantonese`碼表去除聲調後再轉換過來，作爲替代更新，但係目前未確定日期。

**Comment by laubonghaudoi** [comment]
@Raymonf 啱先嘅兩次更新 36bdf05a3184de6b88afcfaa456df02fbd40fc13 3fa96a8405f55b013d90e00524ff6c893b2249f2 已經將`rime-cantonese`嘅數據全部轉移落呢個倉庫入邊，唔該睇下仲有冇問題，如果冇嘅話麻煩關閉咗呢個issue佢。

**Comment by Raymonf** [comment]
@laubonghaudoi 宜家冇問題啦，多謝！
