### ISSUE TITLE
Window下載之後用不到

### ISSUE THREAD

**Issue by DameTime000** [rime/rime-jyutping#27]
我在Window下載不到粵拼版本的輸入法，但在MacOs並沒有這個問題，請問應如何解決 ?

**Comment by laubonghaudoi** [comment]
呢個倉庫已經停止維護，唔該睇[呢度](https://github.com/rime/rime-cantonese/wiki/%E6%96%B0%E6%89%8B%E5%AE%89%E8%A3%9D%E6%95%99%E7%A8%8B)安裝新版嘅，有乜問題都可以入去個 [telegram 羣組](https://t.me/rime_cantonese)度問

**Comment by laubonghaudoi** [comment]
@DameTime000 請問個問題解決未？
